### ISSUE TITLE
RttManagerCompat.getRttCapabilities()

### ISSUE THREAD

**Issue by hjwe** [Plinzen/android-rttmanager-compat#1]
Hi when i use RttManagerCompat.getRttCapabilities() it returns a null value. 
Running on a snapdragon 820 with Nougat 

initialize as below and running in priva-app folder
rttManagerCompat = new RttManagerCompat(getApplicationContext());
RttManagerCompat.getRttCapabilities() 

any insights as to why it doesnt work?

**Comment by Plinzen** [comment]
Hi,
I tested my code only on a Nexus 6P. Basically the function returns `null`, if the call to the internal System-API fails. 

```
    public RttCapabilities getRttCapabilities() {
        try {
            final Object nativeCapabilities = rttManagerClass.getMethod(METHOD_GET_RTT_CAPABILITIES).invoke(rttManager);
            return RttManagerCompatUtil.buildRttCapabilitiesFromNativeObject(nativeCapabilities);
        } catch (IllegalAccessException | InvocationTargetException | NoSuchMethodException e) {
            Log.e(TAG, e.getMessage(), e);
        }
        return null;
}
```
But you should see an error message in your Android Logcat. Does appear anything?

**Comment by hjwe** [comment]
Thanks for the reply! 
I'm trying it on a Mi5 and i get the following logcat error. So it seems the phone does not support this feature =/

> /system_process E/WifiHAL: wifi_get_rtt_capabilities: getLowiCallbackTable returned NULL or the function pointer is NULL. Exit.

originates from 

```
 lowiWifiHalApi = getLowiCallbackTable(
              ONE_SIDED_RANGING_SUPPORTED|DUAL_SIDED_RANGING_SUPPORED);
if (lowiWifiHalApi == NULL ||
   lowiWifiHalApi->get_rtt_capabilities == NULL) {
       ALOGE("wifi_get_rtt_capabilities: getLowiCallbackTable returned NULL or "
           "the function pointer is NULL. Exit.");
       ret = WIFI_ERROR_NOT_SUPPORTED;
      goto cleanup;
}
```

**Comment by hjwe** [comment]
Doesn't the Nexus 6P come with a Snapdragon 810 and not a 820?

**Comment by Plinzen** [comment]
Unfortunately, I don't have a MI5 for testing, so I would agree that it does not support this (still hidden) feature. The Nexus 6P has an Snapdragon 810 platform. But nevertheless we were able to perform a distance calculation between Access Point and phone using this technique. We were not able to use all parameters, which are defined in RttParams class, but basically it was working.

**Comment by Plinzen** [comment]
No update, seems to be fixed.
