### ISSUE TITLE
Can not get RTT capabilities

### ISSUE THREAD

**Issue by zjsheng** [Plinzen/android-rttmanager-compat#4]
Hi,
I used your library and installed it in system/priv-app, but it was wrong
Mobile phone is android7.0
A rooted Android phone
I used isDeviceToApRttSuported, the result is ture

**Comment by zjsheng** [comment]
![qq 20170717100445](https://user-images.githubusercontent.com/16715141/28253528-6ab34c92-6ad7-11e7-9b2e-fff4327565b3.png)

**Comment by zjsheng** [comment]
![1](https://user-images.githubusercontent.com/16715141/28253899-af500fae-6ada-11e7-9a97-3eb5655cec9e.png)

**Comment by Plinzen** [comment]
It seems that the MI5 does not support the RTT feature. Please refer to #1.
The error log tells the same from my point of view.

**Comment by zjsheng** [comment]
Thanks
