### ISSUE TITLE
AP with 802.11MC

### ISSUE THREAD

**Issue by vuongdnguyen** [Plinzen/android-rttmanager-compat#5]
Do you have any recommendation on an AP that would support 802.11MC ?
Also you said any phone with SnapDragon820 would work? Which phone did you try on? Did you try GalaxyS7 ?

**Comment by Plinzen** [comment]
Unfortunately not. We have one with a custom software running on an Intel Galileo platform. But this one is not public available. 
On phone side we tried the ranging with a Nexus 6P and a Pixel. An S7 might work, if you have a version which does not have an Exynos processor. But we haven't tried the S7

**Comment by HappyZ** [comment]
For AP, if I get an Intel 8260 chip, and install it on a laptop, can I configure the laptop to transmit and broadcast 802.11mc beacons? Also @Plinzen is it possible you could share more info about your custom software on Intel Galileo platform?

According to https://wireless.wiki.kernel.org/en/users/drivers/iwlwifi, 
> While we advertise support for Wi-Fi Location* and Wi-Fi Aware* on 8260, we can't commmit on accurate results for those features. NAN isn't considered stable yet and may or may not work depending on the firmware version. FTM can work on 8260 only and requires special calibrations so that an off the shelf 8260 won't be able to provide accurate measurements.

On phone side, this module on Nexus 6 said twoSidedRTT is supported, which I assume would work? Thanks ahead.

**Comment by Plinzen** [comment]
_For AP, if I get an Intel 8260 chip, and install it on a laptop, can I configure the laptop to transmit and broadcast 802.11mc beacons? Also @Plinzen is it possible you could share more info about your custom software on Intel Galileo platform?_
I don't know. I can't share that code. 

_On phone side, this module on Nexus 6 said twoSidedRTT is supported, which I assume would work?_ 
Try it out.
